# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-22 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('light', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='light',
            name='state',
            field=models.CharField(choices=[('ON', 'Allume'), ('OFF', 'Eteint')], default='OFF', max_length=10),
        ),
    ]
