# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-23 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('light', '0002_auto_20181022_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='light',
            name='color',
            field=models.CharField(choices=[('WHITE', 'white'), ('RED', 'red'), ('BLUE', 'blue'), ('GREEN', 'green'), ('YELLOW', 'yellow'), ('PURPLE', 'purple')], default='WHITE', max_length=15),
        ),
    ]
